/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Error in retrieving the specific machine
 */
export type GetApiV1MachinesMachineIdResponseBodyData = {
    error: string;
};

/**
 * Error in retrieving the specific machine
 */
export class GetApiV1MachinesMachineIdResponseBody extends Error {
    error: string;

    /** The original data that was passed to this error instance. */
    data$: GetApiV1MachinesMachineIdResponseBodyData;

    constructor(err: GetApiV1MachinesMachineIdResponseBodyData) {
        const message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : `API error occurred: ${JSON.stringify(err)}`;
        super(message);
        this.data$ = err;

        this.error = err.error;

        this.name = "GetApiV1MachinesMachineIdResponseBody";
    }
}

/** @internal */
export const GetApiV1MachinesMachineIdResponseBody$inboundSchema: z.ZodType<
    GetApiV1MachinesMachineIdResponseBody,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        error: z.string(),
    })
    .transform((v) => {
        return new GetApiV1MachinesMachineIdResponseBody(v);
    });

/** @internal */
export type GetApiV1MachinesMachineIdResponseBody$Outbound = {
    error: string;
};

/** @internal */
export const GetApiV1MachinesMachineIdResponseBody$outboundSchema: z.ZodType<
    GetApiV1MachinesMachineIdResponseBody$Outbound,
    z.ZodTypeDef,
    GetApiV1MachinesMachineIdResponseBody
> = z
    .instanceof(GetApiV1MachinesMachineIdResponseBody)
    .transform((v) => v.data$)
    .pipe(
        z.object({
            error: z.string(),
        })
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiV1MachinesMachineIdResponseBody$ {
    /** @deprecated use `GetApiV1MachinesMachineIdResponseBody$inboundSchema` instead. */
    export const inboundSchema = GetApiV1MachinesMachineIdResponseBody$inboundSchema;
    /** @deprecated use `GetApiV1MachinesMachineIdResponseBody$outboundSchema` instead. */
    export const outboundSchema = GetApiV1MachinesMachineIdResponseBody$outboundSchema;
    /** @deprecated use `GetApiV1MachinesMachineIdResponseBody$Outbound` instead. */
    export type Outbound = GetApiV1MachinesMachineIdResponseBody$Outbound;
}
