/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * error
 */
export type GetApiDeploymentResponseBodyData = {
    error: string;
};

/**
 * error
 */
export class GetApiDeploymentResponseBody extends Error {
    error: string;

    /** The original data that was passed to this error instance. */
    data$: GetApiDeploymentResponseBodyData;

    constructor(err: GetApiDeploymentResponseBodyData) {
        const message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : `API error occurred: ${JSON.stringify(err)}`;
        super(message);
        this.data$ = err;

        this.error = err.error;

        this.name = "GetApiDeploymentResponseBody";
    }
}

/** @internal */
export const GetApiDeploymentResponseBody$inboundSchema: z.ZodType<
    GetApiDeploymentResponseBody,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        error: z.string(),
    })
    .transform((v) => {
        return new GetApiDeploymentResponseBody(v);
    });

/** @internal */
export type GetApiDeploymentResponseBody$Outbound = {
    error: string;
};

/** @internal */
export const GetApiDeploymentResponseBody$outboundSchema: z.ZodType<
    GetApiDeploymentResponseBody$Outbound,
    z.ZodTypeDef,
    GetApiDeploymentResponseBody
> = z
    .instanceof(GetApiDeploymentResponseBody)
    .transform((v) => v.data$)
    .pipe(
        z.object({
            error: z.string(),
        })
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiDeploymentResponseBody$ {
    /** @deprecated use `GetApiDeploymentResponseBody$inboundSchema` instead. */
    export const inboundSchema = GetApiDeploymentResponseBody$inboundSchema;
    /** @deprecated use `GetApiDeploymentResponseBody$outboundSchema` instead. */
    export const outboundSchema = GetApiDeploymentResponseBody$outboundSchema;
    /** @deprecated use `GetApiDeploymentResponseBody$Outbound` instead. */
    export type Outbound = GetApiDeploymentResponseBody$Outbound;
}
