/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Error when uploading the workflow
 */
export type GetDeploymentIdInputsResponseBodyData = {
    error: string;
};

/**
 * Error when uploading the workflow
 */
export class GetDeploymentIdInputsResponseBody extends Error {
    error: string;

    /** The original data that was passed to this error instance. */
    data$: GetDeploymentIdInputsResponseBodyData;

    constructor(err: GetDeploymentIdInputsResponseBodyData) {
        const message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : `API error occurred: ${JSON.stringify(err)}`;
        super(message);
        this.data$ = err;

        this.error = err.error;

        this.name = "GetDeploymentIdInputsResponseBody";
    }
}

/** @internal */
export const GetDeploymentIdInputsResponseBody$inboundSchema: z.ZodType<
    GetDeploymentIdInputsResponseBody,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        error: z.string(),
    })
    .transform((v) => {
        return new GetDeploymentIdInputsResponseBody(v);
    });

/** @internal */
export type GetDeploymentIdInputsResponseBody$Outbound = {
    error: string;
};

/** @internal */
export const GetDeploymentIdInputsResponseBody$outboundSchema: z.ZodType<
    GetDeploymentIdInputsResponseBody$Outbound,
    z.ZodTypeDef,
    GetDeploymentIdInputsResponseBody
> = z
    .instanceof(GetDeploymentIdInputsResponseBody)
    .transform((v) => v.data$)
    .pipe(
        z.object({
            error: z.string(),
        })
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetDeploymentIdInputsResponseBody$ {
    /** @deprecated use `GetDeploymentIdInputsResponseBody$inboundSchema` instead. */
    export const inboundSchema = GetDeploymentIdInputsResponseBody$inboundSchema;
    /** @deprecated use `GetDeploymentIdInputsResponseBody$outboundSchema` instead. */
    export const outboundSchema = GetDeploymentIdInputsResponseBody$outboundSchema;
    /** @deprecated use `GetDeploymentIdInputsResponseBody$Outbound` instead. */
    export type Outbound = GetDeploymentIdInputsResponseBody$Outbound;
}
