/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Error when generating upload url
 */
export type GetUploadUrlResponseBodyData = {
    error: string;
};

/**
 * Error when generating upload url
 */
export class GetUploadUrlResponseBody extends Error {
    error: string;

    /** The original data that was passed to this error instance. */
    data$: GetUploadUrlResponseBodyData;

    constructor(err: GetUploadUrlResponseBodyData) {
        const message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : `API error occurred: ${JSON.stringify(err)}`;
        super(message);
        this.data$ = err;

        this.error = err.error;

        this.name = "GetUploadUrlResponseBody";
    }
}

/** @internal */
export const GetUploadUrlResponseBody$inboundSchema: z.ZodType<
    GetUploadUrlResponseBody,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        error: z.string(),
    })
    .transform((v) => {
        return new GetUploadUrlResponseBody(v);
    });

/** @internal */
export type GetUploadUrlResponseBody$Outbound = {
    error: string;
};

/** @internal */
export const GetUploadUrlResponseBody$outboundSchema: z.ZodType<
    GetUploadUrlResponseBody$Outbound,
    z.ZodTypeDef,
    GetUploadUrlResponseBody
> = z
    .instanceof(GetUploadUrlResponseBody)
    .transform((v) => v.data$)
    .pipe(
        z.object({
            error: z.string(),
        })
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUploadUrlResponseBody$ {
    /** @deprecated use `GetUploadUrlResponseBody$inboundSchema` instead. */
    export const inboundSchema = GetUploadUrlResponseBody$inboundSchema;
    /** @deprecated use `GetUploadUrlResponseBody$outboundSchema` instead. */
    export const outboundSchema = GetUploadUrlResponseBody$outboundSchema;
    /** @deprecated use `GetUploadUrlResponseBody$Outbound` instead. */
    export type Outbound = GetUploadUrlResponseBody$Outbound;
}
