/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Error in retrieving workflows
 */
export type GetV1WorkflowsResponseBodyData = {
    error: string;
};

/**
 * Error in retrieving workflows
 */
export class GetV1WorkflowsResponseBody extends Error {
    error: string;

    /** The original data that was passed to this error instance. */
    data$: GetV1WorkflowsResponseBodyData;

    constructor(err: GetV1WorkflowsResponseBodyData) {
        const message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : `API error occurred: ${JSON.stringify(err)}`;
        super(message);
        this.data$ = err;

        this.error = err.error;

        this.name = "GetV1WorkflowsResponseBody";
    }
}

/** @internal */
export const GetV1WorkflowsResponseBody$inboundSchema: z.ZodType<
    GetV1WorkflowsResponseBody,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        error: z.string(),
    })
    .transform((v) => {
        return new GetV1WorkflowsResponseBody(v);
    });

/** @internal */
export type GetV1WorkflowsResponseBody$Outbound = {
    error: string;
};

/** @internal */
export const GetV1WorkflowsResponseBody$outboundSchema: z.ZodType<
    GetV1WorkflowsResponseBody$Outbound,
    z.ZodTypeDef,
    GetV1WorkflowsResponseBody
> = z
    .instanceof(GetV1WorkflowsResponseBody)
    .transform((v) => v.data$)
    .pipe(
        z.object({
            error: z.string(),
        })
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV1WorkflowsResponseBody$ {
    /** @deprecated use `GetV1WorkflowsResponseBody$inboundSchema` instead. */
    export const inboundSchema = GetV1WorkflowsResponseBody$inboundSchema;
    /** @deprecated use `GetV1WorkflowsResponseBody$outboundSchema` instead. */
    export const outboundSchema = GetV1WorkflowsResponseBody$outboundSchema;
    /** @deprecated use `GetV1WorkflowsResponseBody$Outbound` instead. */
    export type Outbound = GetV1WorkflowsResponseBody$Outbound;
}
