/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Error creating run
 */
export type GetWebsocketDeploymentIdResponseBodyData = {
  error: string;
};

/**
 * Error creating run
 */
export class GetWebsocketDeploymentIdResponseBody extends Error {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: GetWebsocketDeploymentIdResponseBodyData;

  constructor(err: GetWebsocketDeploymentIdResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "GetWebsocketDeploymentIdResponseBody";
  }
}

/** @internal */
export const GetWebsocketDeploymentIdResponseBody$inboundSchema: z.ZodType<
  GetWebsocketDeploymentIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string(),
})
  .transform((v) => {
    return new GetWebsocketDeploymentIdResponseBody(v);
  });

/** @internal */
export type GetWebsocketDeploymentIdResponseBody$Outbound = {
  error: string;
};

/** @internal */
export const GetWebsocketDeploymentIdResponseBody$outboundSchema: z.ZodType<
  GetWebsocketDeploymentIdResponseBody$Outbound,
  z.ZodTypeDef,
  GetWebsocketDeploymentIdResponseBody
> = z.instanceof(GetWebsocketDeploymentIdResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWebsocketDeploymentIdResponseBody$ {
  /** @deprecated use `GetWebsocketDeploymentIdResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    GetWebsocketDeploymentIdResponseBody$inboundSchema;
  /** @deprecated use `GetWebsocketDeploymentIdResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    GetWebsocketDeploymentIdResponseBody$outboundSchema;
  /** @deprecated use `GetWebsocketDeploymentIdResponseBody$Outbound` instead. */
  export type Outbound = GetWebsocketDeploymentIdResponseBody$Outbound;
}
