/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Error in creating workflow
 */
export type PostApiV1WorkflowsResponseBodyData = {
    error: string;
};

/**
 * Error in creating workflow
 */
export class PostApiV1WorkflowsResponseBody extends Error {
    error: string;

    /** The original data that was passed to this error instance. */
    data$: PostApiV1WorkflowsResponseBodyData;

    constructor(err: PostApiV1WorkflowsResponseBodyData) {
        const message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : `API error occurred: ${JSON.stringify(err)}`;
        super(message);
        this.data$ = err;

        this.error = err.error;

        this.name = "PostApiV1WorkflowsResponseBody";
    }
}

/** @internal */
export const PostApiV1WorkflowsResponseBody$inboundSchema: z.ZodType<
    PostApiV1WorkflowsResponseBody,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        error: z.string(),
    })
    .transform((v) => {
        return new PostApiV1WorkflowsResponseBody(v);
    });

/** @internal */
export type PostApiV1WorkflowsResponseBody$Outbound = {
    error: string;
};

/** @internal */
export const PostApiV1WorkflowsResponseBody$outboundSchema: z.ZodType<
    PostApiV1WorkflowsResponseBody$Outbound,
    z.ZodTypeDef,
    PostApiV1WorkflowsResponseBody
> = z
    .instanceof(PostApiV1WorkflowsResponseBody)
    .transform((v) => v.data$)
    .pipe(
        z.object({
            error: z.string(),
        })
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiV1WorkflowsResponseBody$ {
    /** @deprecated use `PostApiV1WorkflowsResponseBody$inboundSchema` instead. */
    export const inboundSchema = PostApiV1WorkflowsResponseBody$inboundSchema;
    /** @deprecated use `PostApiV1WorkflowsResponseBody$outboundSchema` instead. */
    export const outboundSchema = PostApiV1WorkflowsResponseBody$outboundSchema;
    /** @deprecated use `PostApiV1WorkflowsResponseBody$Outbound` instead. */
    export type Outbound = PostApiV1WorkflowsResponseBody$Outbound;
}
