/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Error creating run
 */
export type PostApiRunResponseBodyData = {
    error: string;
};

/**
 * Error creating run
 */
export class PostApiRunResponseBody extends Error {
    error: string;

    /** The original data that was passed to this error instance. */
    data$: PostApiRunResponseBodyData;

    constructor(err: PostApiRunResponseBodyData) {
        const message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : `API error occurred: ${JSON.stringify(err)}`;
        super(message);
        this.data$ = err;

        this.error = err.error;

        this.name = "PostApiRunResponseBody";
    }
}

/** @internal */
export const PostApiRunResponseBody$inboundSchema: z.ZodType<
    PostApiRunResponseBody,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        error: z.string(),
    })
    .transform((v) => {
        return new PostApiRunResponseBody(v);
    });

/** @internal */
export type PostApiRunResponseBody$Outbound = {
    error: string;
};

/** @internal */
export const PostApiRunResponseBody$outboundSchema: z.ZodType<
    PostApiRunResponseBody$Outbound,
    z.ZodTypeDef,
    PostApiRunResponseBody
> = z
    .instanceof(PostApiRunResponseBody)
    .transform((v) => v.data$)
    .pipe(
        z.object({
            error: z.string(),
        })
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiRunResponseBody$ {
    /** @deprecated use `PostApiRunResponseBody$inboundSchema` instead. */
    export const inboundSchema = PostApiRunResponseBody$inboundSchema;
    /** @deprecated use `PostApiRunResponseBody$outboundSchema` instead. */
    export const outboundSchema = PostApiRunResponseBody$outboundSchema;
    /** @deprecated use `PostApiRunResponseBody$Outbound` instead. */
    export type Outbound = PostApiRunResponseBody$Outbound;
}
