/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deploymentsUpdate } from "../../funcs/deploymentsUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.UpdateDeploymentDeploymentDeploymentIdPatchRequest$inboundSchema,
};

export const tool$deploymentsUpdate: ToolDefinition<typeof args> = {
  name: "deployments_update",
  description: `Update Deployment`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await deploymentsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
