/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deploymentsDeactivate } from "../../funcs/deploymentsDeactivate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations
      .DeactivateDeploymentDeploymentDeploymentIdDeactivatePostRequest$inboundSchema,
};

export const tool$deploymentsDeactivate: ToolDefinition<typeof args> = {
  name: "deployments-deactivate",
  description: `Deactivate Deployment`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await deploymentsDeactivate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
