/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deploymentsGetFeaturedDeploymentsDeploymentsFeaturedGet } from "../../funcs/deploymentsGetFeaturedDeploymentsDeploymentsFeaturedGet.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$deploymentsGetFeaturedDeploymentsDeploymentsFeaturedGet:
  ToolDefinition = {
    name: "deployments_get-featured-deployments-deployments-featured-get",
    description: `Get Featured Deployments`,
    tool: async (client, ctx) => {
      const [result, apiCall] =
        await deploymentsGetFeaturedDeploymentsDeploymentsFeaturedGet(
          client,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
