/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { fileUploadAssetFileAssetsUploadPost } from "../../funcs/fileUploadAssetFileAssetsUploadPost.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UploadAssetFileAssetsUploadPostRequest$inboundSchema,
};

export const tool$fileUploadAssetFileAssetsUploadPost: ToolDefinition<
  typeof args
> = {
  name: "file_upload-asset-file-assets-upload-post",
  description: `Upload Asset File`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await fileUploadAssetFileAssetsUploadPost(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
