/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { fileDeleteAssetAssetsAssetIdDelete } from "../../funcs/fileDeleteAssetAssetsAssetIdDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteAssetAssetsAssetIdDeleteRequest$inboundSchema,
};

export const tool$fileDeleteAssetAssetsAssetIdDelete: ToolDefinition<
  typeof args
> = {
  name: "file-delete-asset-assets-asset-id-delete",
  description: `Delete Asset`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await fileDeleteAssetAssetsAssetIdDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
