/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { fileGetAssetAssetsAssetIdGet } from "../../funcs/fileGetAssetAssetsAssetIdGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAssetAssetsAssetIdGetRequest$inboundSchema,
};

export const tool$fileGetAssetAssetsAssetIdGet: ToolDefinition<typeof args> = {
  name: "file-get-asset-assets-asset-id-get",
  description: `Get Asset`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await fileGetAssetAssetsAssetIdGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
