/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { runDeploymentSync } from "../../funcs/runDeploymentSync.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.DeploymentRunRequest$inboundSchema,
};

export const tool$runDeploymentSync: ToolDefinition<typeof args> = {
  name: "run-deployment_sync",
  description: `Deployment - Sync

Create a new deployment run with the given parameters.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await runDeploymentSync(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
