/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { runWorkflowSync } from "../../funcs/runWorkflowSync.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.WorkflowRunRequest$inboundSchema,
};

export const tool$runWorkflowSync: ToolDefinition<typeof args> = {
  name: "run-workflow_sync",
  description: `Workflow - Sync

Create a new workflow run with the given parameters.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await runWorkflowSync(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
