/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { searchSearchSearchModelGet } from "../../funcs/searchSearchSearchModelGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SearchSearchModelGetRequest$inboundSchema,
};

export const tool$searchSearchSearchModelGet: ToolDefinition<typeof args> = {
  name: "search-search-search-model-get",
  description: `Search`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await searchSearchSearchModelGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
