/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sessionCreate } from "../../funcs/sessionCreate.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.CreateSessionBody$inboundSchema,
};

export const tool$sessionCreate: ToolDefinition<typeof args> = {
  name: "session-create",
  description: `Create Session`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sessionCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
