/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { ComfyDeployCore } from "../core.js";
import { deploymentRunsSync } from "../funcs/deploymentRunsSync.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useComfyDeployContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type DeploymentRunsSyncMutationVariables = {
  request: components.DeploymentRunRequest;
  options?: RequestOptions;
};

export type DeploymentRunsSyncMutationData = Array<
  components.WorkflowRunOutputModel
>;

/**
 * Deployment - Sync
 *
 * @remarks
 * Create a new deployment run with the given parameters.
 */
export function useDeploymentRunsSyncMutation(
  options?: MutationHookOptions<
    DeploymentRunsSyncMutationData,
    Error,
    DeploymentRunsSyncMutationVariables
  >,
): UseMutationResult<
  DeploymentRunsSyncMutationData,
  Error,
  DeploymentRunsSyncMutationVariables
> {
  const client = useComfyDeployContext();
  return useMutation({
    ...buildDeploymentRunsSyncMutation(client, options),
    ...options,
  });
}

export function mutationKeyDeploymentRunsSync(): MutationKey {
  return ["comfydeploy", "deploymentRuns", "sync"];
}

export function buildDeploymentRunsSyncMutation(
  client$: ComfyDeployCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: DeploymentRunsSyncMutationVariables,
  ) => Promise<DeploymentRunsSyncMutationData>;
} {
  return {
    mutationKey: mutationKeyDeploymentRunsSync(),
    mutationFn: function deploymentRunsSyncMutationFn({
      request,
      options,
    }): Promise<DeploymentRunsSyncMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(deploymentRunsSync(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
