/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { ComfyDeployCore } from "../core.js";
import { deploymentsGet } from "../funcs/deploymentsGet.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useComfyDeployContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type DeploymentsGetQueryData = components.DeploymentModel;

/**
 * Get Deployment
 */
export function useDeploymentsGet(
  request: operations.GetDeploymentDeploymentDeploymentIdGetRequest,
  options?: QueryHookOptions<DeploymentsGetQueryData>,
): UseQueryResult<DeploymentsGetQueryData, Error> {
  const client = useComfyDeployContext();
  return useQuery({
    ...buildDeploymentsGetQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get Deployment
 */
export function useDeploymentsGetSuspense(
  request: operations.GetDeploymentDeploymentDeploymentIdGetRequest,
  options?: SuspenseQueryHookOptions<DeploymentsGetQueryData>,
): UseSuspenseQueryResult<DeploymentsGetQueryData, Error> {
  const client = useComfyDeployContext();
  return useSuspenseQuery({
    ...buildDeploymentsGetQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function prefetchDeploymentsGet(
  queryClient: QueryClient,
  client$: ComfyDeployCore,
  request: operations.GetDeploymentDeploymentDeploymentIdGetRequest,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildDeploymentsGetQuery(
      client$,
      request,
    ),
  });
}

export function setDeploymentsGetData(
  client: QueryClient,
  queryKeyBase: [deploymentId: string],
  data: DeploymentsGetQueryData,
): DeploymentsGetQueryData | undefined {
  const key = queryKeyDeploymentsGet(...queryKeyBase);

  return client.setQueryData<DeploymentsGetQueryData>(key, data);
}

export function invalidateDeploymentsGet(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[deploymentId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["comfydeploy", "Deployments", "get", ...queryKeyBase],
  });
}

export function invalidateAllDeploymentsGet(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["comfydeploy", "Deployments", "get"],
  });
}

export function buildDeploymentsGetQuery(
  client$: ComfyDeployCore,
  request: operations.GetDeploymentDeploymentDeploymentIdGetRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<DeploymentsGetQueryData>;
} {
  return {
    queryKey: queryKeyDeploymentsGet(request.deploymentId),
    queryFn: async function deploymentsGetQueryFn(
      ctx,
    ): Promise<DeploymentsGetQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(deploymentsGet(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyDeploymentsGet(deploymentId: string): QueryKey {
  return ["comfydeploy", "Deployments", "get", deploymentId];
}
