/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { ComfyDeployCore } from "../core.js";
import { filesUploadFile } from "../funcs/filesUploadFile.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useComfyDeployContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type FilesUploadFileMutationVariables = {
  request: components.BodyUploadFileFileUploadPost;
  options?: RequestOptions;
};

export type FilesUploadFileMutationData = components.FileUploadResponse;

/**
 * Upload File
 */
export function useFilesUploadFileMutation(
  options?: MutationHookOptions<
    FilesUploadFileMutationData,
    Error,
    FilesUploadFileMutationVariables
  >,
): UseMutationResult<
  FilesUploadFileMutationData,
  Error,
  FilesUploadFileMutationVariables
> {
  const client = useComfyDeployContext();
  return useMutation({
    ...buildFilesUploadFileMutation(client, options),
    ...options,
  });
}

export function mutationKeyFilesUploadFile(): MutationKey {
  return ["comfydeploy", "files", "uploadFile"];
}

export function buildFilesUploadFileMutation(
  client$: ComfyDeployCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: FilesUploadFileMutationVariables,
  ) => Promise<FilesUploadFileMutationData>;
} {
  return {
    mutationKey: mutationKeyFilesUploadFile(),
    mutationFn: function filesUploadFileMutationFn({
      request,
      options,
    }): Promise<FilesUploadFileMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(filesUploadFile(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
