/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { ComfyDeployCore } from "../core.js";
import { fileUpload } from "../funcs/fileUpload.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useComfyDeployContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type FileUploadMutationVariables = {
  request: components.BodyUploadFileFileUploadPost;
  options?: RequestOptions;
};

export type FileUploadMutationData = components.FileUploadResponse;

/**
 * Upload File
 */
export function useFileUploadMutation(
  options?: MutationHookOptions<
    FileUploadMutationData,
    Error,
    FileUploadMutationVariables
  >,
): UseMutationResult<
  FileUploadMutationData,
  Error,
  FileUploadMutationVariables
> {
  const client = useComfyDeployContext();
  return useMutation({
    ...buildFileUploadMutation(client, options),
    ...options,
  });
}

export function mutationKeyFileUpload(): MutationKey {
  return ["comfydeploy", "File", "upload"];
}

export function buildFileUploadMutation(
  client$: ComfyDeployCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: FileUploadMutationVariables,
  ) => Promise<FileUploadMutationData>;
} {
  return {
    mutationKey: mutationKeyFileUpload(),
    mutationFn: function fileUploadMutationFn({
      request,
      options,
    }): Promise<FileUploadMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(fileUpload(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
