/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { ComfyDeployCore } from "../core.js";
import { filesCreateFolder } from "../funcs/filesCreateFolder.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useComfyDeployContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type FilesCreateFolderMutationVariables = {
  request: components.CreateFolderRequest;
  options?: RequestOptions;
};

export type FilesCreateFolderMutationData = components.AssetResponse;

/**
 * Create Folder
 */
export function useFilesCreateFolderMutation(
  options?: MutationHookOptions<
    FilesCreateFolderMutationData,
    Error,
    FilesCreateFolderMutationVariables
  >,
): UseMutationResult<
  FilesCreateFolderMutationData,
  Error,
  FilesCreateFolderMutationVariables
> {
  const client = useComfyDeployContext();
  return useMutation({
    ...buildFilesCreateFolderMutation(client, options),
    ...options,
  });
}

export function mutationKeyFilesCreateFolder(): MutationKey {
  return ["comfydeploy", "files", "createFolder"];
}

export function buildFilesCreateFolderMutation(
  client$: ComfyDeployCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: FilesCreateFolderMutationVariables,
  ) => Promise<FilesCreateFolderMutationData>;
} {
  return {
    mutationKey: mutationKeyFilesCreateFolder(),
    mutationFn: function filesCreateFolderMutationFn({
      request,
      options,
    }): Promise<FilesCreateFolderMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(filesCreateFolder(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
