/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { ComfyDeployCore } from "../core.js";
import { runDeploymentStream } from "../funcs/runDeploymentStream.js";
import { EventStream } from "../lib/event-streams.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useComfyDeployContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type RunDeploymentStreamMutationVariables = {
  request: components.DeploymentRunRequest;
  options?: RequestOptions;
};

export type RunDeploymentStreamMutationData = EventStream<components.RunStream>;

/**
 * Deployment - Stream
 *
 * @remarks
 * Create a new deployment run with the given parameters. This function sets up the run and initiates the execution process. For callback information, see [Callbacks](#tag/callbacks/POST/\{callback_url\}).
 */
export function useRunDeploymentStreamMutation(
  options?: MutationHookOptions<
    RunDeploymentStreamMutationData,
    Error,
    RunDeploymentStreamMutationVariables
  >,
): UseMutationResult<
  RunDeploymentStreamMutationData,
  Error,
  RunDeploymentStreamMutationVariables
> {
  const client = useComfyDeployContext();
  return useMutation({
    ...buildRunDeploymentStreamMutation(client, options),
    ...options,
  });
}

export function mutationKeyRunDeploymentStream(): MutationKey {
  return ["comfydeploy", "deployment", "stream"];
}

export function buildRunDeploymentStreamMutation(
  client$: ComfyDeployCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: RunDeploymentStreamMutationVariables,
  ) => Promise<RunDeploymentStreamMutationData>;
} {
  return {
    mutationKey: mutationKeyRunDeploymentStream(),
    mutationFn: function runDeploymentStreamMutationFn({
      request,
      options,
    }): Promise<RunDeploymentStreamMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(runDeploymentStream(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
