/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { ComfyDeployCore } from "../core.js";
import { runWorkflowQueue } from "../funcs/runWorkflowQueue.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useComfyDeployContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type RunWorkflowQueueMutationVariables = {
  request: components.WorkflowRunRequest;
  options?: RequestOptions;
};

export type RunWorkflowQueueMutationData = components.CreateRunResponse;

/**
 * Workflow - Queue
 *
 * @remarks
 * Create a new workflow run with the given parameters.
 */
export function useRunWorkflowQueueMutation(
  options?: MutationHookOptions<
    RunWorkflowQueueMutationData,
    Error,
    RunWorkflowQueueMutationVariables
  >,
): UseMutationResult<
  RunWorkflowQueueMutationData,
  Error,
  RunWorkflowQueueMutationVariables
> {
  const client = useComfyDeployContext();
  return useMutation({
    ...buildRunWorkflowQueueMutation(client, options),
    ...options,
  });
}

export function mutationKeyRunWorkflowQueue(): MutationKey {
  return ["comfydeploy", "runWorkflow", "queue"];
}

export function buildRunWorkflowQueueMutation(
  client$: ComfyDeployCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: RunWorkflowQueueMutationVariables,
  ) => Promise<RunWorkflowQueueMutationData>;
} {
  return {
    mutationKey: mutationKeyRunWorkflowQueue(),
    mutationFn: function runWorkflowQueueMutationFn({
      request,
      options,
    }): Promise<RunWorkflowQueueMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(runWorkflowQueue(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
