/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { ComfyDeployCore } from "../core.js";
import { runWorkflowStream } from "../funcs/runWorkflowStream.js";
import { EventStream } from "../lib/event-streams.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useComfyDeployContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type RunWorkflowStreamMutationVariables = {
  request: components.WorkflowRunRequest;
  options?: RequestOptions;
};

export type RunWorkflowStreamMutationData = EventStream<components.RunStream>;

/**
 * Workflow - Stream
 *
 * @remarks
 * Create a new workflow run with the given parameters. This function sets up the run and initiates the execution process. For callback information, see [Callbacks](#tag/callbacks/POST/\{callback_url\}).
 */
export function useRunWorkflowStreamMutation(
  options?: MutationHookOptions<
    RunWorkflowStreamMutationData,
    Error,
    RunWorkflowStreamMutationVariables
  >,
): UseMutationResult<
  RunWorkflowStreamMutationData,
  Error,
  RunWorkflowStreamMutationVariables
> {
  const client = useComfyDeployContext();
  return useMutation({
    ...buildRunWorkflowStreamMutation(client, options),
    ...options,
  });
}

export function mutationKeyRunWorkflowStream(): MutationKey {
  return ["comfydeploy", "workflow", "stream"];
}

export function buildRunWorkflowStreamMutation(
  client$: ComfyDeployCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: RunWorkflowStreamMutationVariables,
  ) => Promise<RunWorkflowStreamMutationData>;
} {
  return {
    mutationKey: mutationKeyRunWorkflowStream(),
    mutationFn: function runWorkflowStreamMutationFn({
      request,
      options,
    }): Promise<RunWorkflowStreamMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(runWorkflowStream(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
