/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { ComfyDeployCore } from "../core.js";
import { sessionCreate } from "../funcs/sessionCreate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useComfyDeployContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type SessionCreateMutationVariables = {
  request: components.CreateSessionBody;
  options?: RequestOptions;
};

export type SessionCreateMutationData = components.CreateSessionResponse;

/**
 * Create Session
 */
export function useSessionCreateMutation(
  options?: MutationHookOptions<
    SessionCreateMutationData,
    Error,
    SessionCreateMutationVariables
  >,
): UseMutationResult<
  SessionCreateMutationData,
  Error,
  SessionCreateMutationVariables
> {
  const client = useComfyDeployContext();
  return useMutation({
    ...buildSessionCreateMutation(client, options),
    ...options,
  });
}

export function mutationKeySessionCreate(): MutationKey {
  return ["comfydeploy", "Session", "create"];
}

export function buildSessionCreateMutation(
  client$: ComfyDeployCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: SessionCreateMutationVariables,
  ) => Promise<SessionCreateMutationData>;
} {
  return {
    mutationKey: mutationKeySessionCreate(),
    mutationFn: function sessionCreateMutationFn({
      request,
      options,
    }): Promise<SessionCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(sessionCreate(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
