/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

/**
 * The updated run information
 */
export type CreateRunQueueRunQueuePostRunUpdateWebhookRequestBodyWebhookPostBody =
  {
    status: components.WorkflowRunStatus;
    liveStatus: string;
    progress: number;
    runId: string;
    outputs: components.WorkflowRunOutput;
  };

/** @internal */
export const CreateRunQueueRunQueuePostRunUpdateWebhookRequestBodyWebhookPostBody$inboundSchema:
  z.ZodType<
    CreateRunQueueRunQueuePostRunUpdateWebhookRequestBodyWebhookPostBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    status: components.WorkflowRunStatus$inboundSchema,
    live_status: z.string(),
    progress: z.number(),
    run_id: z.string(),
    outputs: components.WorkflowRunOutput$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "live_status": "liveStatus",
      "run_id": "runId",
    });
  });

/** @internal */
export type CreateRunQueueRunQueuePostRunUpdateWebhookRequestBodyWebhookPostBody$Outbound =
  {
    status: string;
    live_status: string;
    progress: number;
    run_id: string;
    outputs: components.WorkflowRunOutput$Outbound;
  };

/** @internal */
export const CreateRunQueueRunQueuePostRunUpdateWebhookRequestBodyWebhookPostBody$outboundSchema:
  z.ZodType<
    CreateRunQueueRunQueuePostRunUpdateWebhookRequestBodyWebhookPostBody$Outbound,
    z.ZodTypeDef,
    CreateRunQueueRunQueuePostRunUpdateWebhookRequestBodyWebhookPostBody
  > = z.object({
    status: components.WorkflowRunStatus$outboundSchema,
    liveStatus: z.string(),
    progress: z.number(),
    runId: z.string(),
    outputs: components.WorkflowRunOutput$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      liveStatus: "live_status",
      runId: "run_id",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateRunQueueRunQueuePostRunUpdateWebhookRequestBodyWebhookPostBody$ {
  /** @deprecated use `CreateRunQueueRunQueuePostRunUpdateWebhookRequestBodyWebhookPostBody$inboundSchema` instead. */
  export const inboundSchema =
    CreateRunQueueRunQueuePostRunUpdateWebhookRequestBodyWebhookPostBody$inboundSchema;
  /** @deprecated use `CreateRunQueueRunQueuePostRunUpdateWebhookRequestBodyWebhookPostBody$outboundSchema` instead. */
  export const outboundSchema =
    CreateRunQueueRunQueuePostRunUpdateWebhookRequestBodyWebhookPostBody$outboundSchema;
  /** @deprecated use `CreateRunQueueRunQueuePostRunUpdateWebhookRequestBodyWebhookPostBody$Outbound` instead. */
  export type Outbound =
    CreateRunQueueRunQueuePostRunUpdateWebhookRequestBodyWebhookPostBody$Outbound;
}
