/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { betaCreateDynamic } from "../funcs/betaCreateDynamic.js";
import { betaGenerateDockerSteps } from "../funcs/betaGenerateDockerSteps.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Beta extends ClientSDK {
  /**
   * Convert To Docker Steps
   */
  async generateDockerSteps(
    request: components.DepsBody,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(betaGenerateDockerSteps(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Dynamic Session
   */
  async createDynamic(
    request: components.CreateDynamicSessionBody,
    options?: RequestOptions,
  ): Promise<components.CreateSessionResponse> {
    return unwrapAsync(betaCreateDynamic(
      this,
      request,
      options,
    ));
  }
}
