/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { fileUpload } from "../funcs/fileUpload.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class FileT extends ClientSDK {
  /**
   * Upload File
   */
  async upload(
    request: components.BodyUploadFileFileUploadPost,
    options?: RequestOptions,
  ): Promise<components.FileUploadResponse> {
    return unwrapAsync(fileUpload(
      this,
      request,
      options,
    ));
  }
}
