/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { machinesGetV1Machines } from "../funcs/machinesGetV1Machines.js";
import { machinesGetV1MachinesMachineId } from "../funcs/machinesGetV1MachinesMachineId.js";
import { machinesPostGpuEvent } from "../funcs/machinesPostGpuEvent.js";
import { machinesPostV1Machines } from "../funcs/machinesPostV1Machines.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Machines extends ClientSDK {
    /**
     * Register a machine event
     */
    async postGpuEvent(
        request?: operations.PostGpuEventRequestBody | undefined,
        options?: RequestOptions
    ): Promise<operations.PostGpuEventResponseBody> {
        return unwrapAsync(machinesPostGpuEvent(this, request, options));
    }

    /**
     * Retrieve all machines for a user
     *
     * @remarks
     * Retrieve details of all machines for the authenticated user, with pagination and optional field selection
     */
    async getV1Machines(
        request: operations.GetV1MachinesRequest,
        options?: RequestOptions
    ): Promise<operations.GetV1MachinesResponseBody> {
        return unwrapAsync(machinesGetV1Machines(this, request, options));
    }

    /**
     * Create a new machine
     *
     * @remarks
     * Create a new machine with optional default setting
     */
    async postV1Machines(
        request?: operations.PostV1MachinesRequestBody | undefined,
        options?: RequestOptions
    ): Promise<operations.PostV1MachinesResponseBody> {
        return unwrapAsync(machinesPostV1Machines(this, request, options));
    }

    /**
     * Retrieve a specific machine by ID
     *
     * @remarks
     * Retrieve details of a specific machine by its ID, with optional workspace details
     */
    async getV1MachinesMachineId(
        request: operations.GetV1MachinesMachineIdRequest,
        options?: RequestOptions
    ): Promise<operations.GetV1MachinesMachineIdResponseBody> {
        return unwrapAsync(machinesGetV1MachinesMachineId(this, request, options));
    }
}
