/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { runsCancel } from "../funcs/runsCancel.js";
import { runsStream } from "../funcs/runsStream.js";
import { EventStream } from "../lib/event-streams.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Runs extends ClientSDK {
  /**
   * Run a workflow in stream
   *
   * @remarks
   * Create a new workflow run with the given parameters. This function sets up the run and initiates the execution process. For callback information, see [Callbacks](#tag/callbacks/POST/\{callback_url\}).
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async stream(
    request: operations.CreateRunStreamRunStreamPostData,
    options?: RequestOptions,
  ): Promise<EventStream<components.RunStream>> {
    return unwrapAsync(runsStream(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel Run
   */
  async cancel(
    request: operations.CancelRunRunRunIdCancelPostRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(runsCancel(
      this,
      request,
      options,
    ));
  }
}
