/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Deployments } from "./deployments.js";
import { FileT } from "./file.js";
import { Models } from "./models.js";
import { Run } from "./run.js";
import { Search } from "./search.js";
import { Session } from "./session.js";

export class ComfyDeploy extends ClientSDK {
  private _run?: Run;
  get run(): Run {
    return (this._run ??= new Run(this._options));
  }

  private _session?: Session;
  get session(): Session {
    return (this._session ??= new Session(this._options));
  }

  private _deployments?: Deployments;
  get deployments(): Deployments {
    return (this._deployments ??= new Deployments(this._options));
  }

  private _file?: FileT;
  get file(): FileT {
    return (this._file ??= new FileT(this._options));
  }

  private _models?: Models;
  get models(): Models {
    return (this._models ??= new Models(this._options));
  }

  private _search?: Search;
  get search(): Search {
    return (this._search ??= new Search(this._options));
  }
}
