/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Comfyui } from "./comfyui.js";
import { Deployment } from "./deployment.js";
import { Files } from "./files.js";
import { Machine } from "./machine.js";
import { Run } from "./run.js";
import { Websocket } from "./websocket.js";
import { Workflows } from "./workflows.js";

export class ComfyDeploy extends ClientSDK {
  private _run?: Run;
  get run(): Run {
    return (this._run ??= new Run(this._options));
  }

  private _files?: Files;
  get files(): Files {
    return (this._files ??= new Files(this._options));
  }

  private _websocket?: Websocket;
  get websocket(): Websocket {
    return (this._websocket ??= new Websocket(this._options));
  }

  private _comfyui?: Comfyui;
  get comfyui(): Comfyui {
    return (this._comfyui ??= new Comfyui(this._options));
  }

  private _workflows?: Workflows;
  get workflows(): Workflows {
    return (this._workflows ??= new Workflows(this._options));
  }

  private _deployment?: Deployment;
  get deployment(): Deployment {
    return (this._deployment ??= new Deployment(this._options));
  }

  private _machine?: Machine;
  get machine(): Machine {
    return (this._machine ??= new Machine(this._options));
  }
}
