/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sessionCancel } from "../funcs/sessionCancel.js";
import { sessionCreate } from "../funcs/sessionCreate.js";
import { sessionGet } from "../funcs/sessionGet.js";
import { sessionList } from "../funcs/sessionList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Session extends ClientSDK {
  /**
   * Get Session
   */
  async get(
    request: operations.GetSessionSessionSessionIdGetRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(sessionGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Session
   */
  async cancel(
    request: operations.DeleteSessionSessionSessionIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(sessionCancel(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Machine Sessions
   */
  async list(
    request: operations.GetMachineSessionsMachineMachineIdSessionsGetRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(sessionList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Session
   */
  async create(
    request: operations.CreateSessionMachineMachineIdSessionPostRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(sessionCreate(
      this,
      request,
      options,
    ));
  }
}
