workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    comfydeploy-api:
        inputs:
            - location: http://localhost:3010/api/openapi.json
        registry:
            location: registry.speakeasyapi.dev/comfydeploy/comfydeploy/comfydeploy-api
targets:
    comfydeploy:
        target: typescript
        source: comfydeploy-api
