workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    comfydeploy-api:
        inputs:
            - location: https://www.comfydeploy.com/api/doc
        registry:
            location: registry.speakeasyapi.dev/comfydeploy/comfydeploy/comfydeploy-api
targets:
    comfy-deploy:
        target: typescript
        source: comfydeploy-api
        publish:
            npm:
                token: $npm_token
