workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    comfydeploy-api:
        inputs:
            - location: https://api.comfydeploy.com/openapi.json/with-no-code-samples
        overlays:
            - location: .speakeasy/openapi-overlay.yaml
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/comfydeploy/comfydeploy/comfydeploy-api
targets:
    comfydeploy:
        target: typescript
        source: comfydeploy-api
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/comfydeploy/comfydeploy/code-samples-typescript-comfydeploy
            labelOverride:
                fixedValue: SDK (TypeScript)
