/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";

export type CreateRunSyncRunSyncPostData =
  | components.DeploymentRunRequest
  | components.WorkflowRunVersionRequest
  | components.WorkflowRunRequest;

/** @internal */
export const CreateRunSyncRunSyncPostData$inboundSchema: z.ZodType<
  CreateRunSyncRunSyncPostData,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.DeploymentRunRequest$inboundSchema,
  components.WorkflowRunVersionRequest$inboundSchema,
  components.WorkflowRunRequest$inboundSchema,
]);

/** @internal */
export type CreateRunSyncRunSyncPostData$Outbound =
  | components.DeploymentRunRequest$Outbound
  | components.WorkflowRunVersionRequest$Outbound
  | components.WorkflowRunRequest$Outbound;

/** @internal */
export const CreateRunSyncRunSyncPostData$outboundSchema: z.ZodType<
  CreateRunSyncRunSyncPostData$Outbound,
  z.ZodTypeDef,
  CreateRunSyncRunSyncPostData
> = z.union([
  components.DeploymentRunRequest$outboundSchema,
  components.WorkflowRunVersionRequest$outboundSchema,
  components.WorkflowRunRequest$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateRunSyncRunSyncPostData$ {
  /** @deprecated use `CreateRunSyncRunSyncPostData$inboundSchema` instead. */
  export const inboundSchema = CreateRunSyncRunSyncPostData$inboundSchema;
  /** @deprecated use `CreateRunSyncRunSyncPostData$outboundSchema` instead. */
  export const outboundSchema = CreateRunSyncRunSyncPostData$outboundSchema;
  /** @deprecated use `CreateRunSyncRunSyncPostData$Outbound` instead. */
  export type Outbound = CreateRunSyncRunSyncPostData$Outbound;
}
