/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetAssetAssetsAssetIdGetRequest = {
  assetId: string;
};

/** @internal */
export const GetAssetAssetsAssetIdGetRequest$inboundSchema: z.ZodType<
  GetAssetAssetsAssetIdGetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  asset_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "asset_id": "assetId",
  });
});

/** @internal */
export type GetAssetAssetsAssetIdGetRequest$Outbound = {
  asset_id: string;
};

/** @internal */
export const GetAssetAssetsAssetIdGetRequest$outboundSchema: z.ZodType<
  GetAssetAssetsAssetIdGetRequest$Outbound,
  z.ZodTypeDef,
  GetAssetAssetsAssetIdGetRequest
> = z.object({
  assetId: z.string(),
}).transform((v) => {
  return remap$(v, {
    assetId: "asset_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAssetAssetsAssetIdGetRequest$ {
  /** @deprecated use `GetAssetAssetsAssetIdGetRequest$inboundSchema` instead. */
  export const inboundSchema = GetAssetAssetsAssetIdGetRequest$inboundSchema;
  /** @deprecated use `GetAssetAssetsAssetIdGetRequest$outboundSchema` instead. */
  export const outboundSchema = GetAssetAssetsAssetIdGetRequest$outboundSchema;
  /** @deprecated use `GetAssetAssetsAssetIdGetRequest$Outbound` instead. */
  export type Outbound = GetAssetAssetsAssetIdGetRequest$Outbound;
}

export function getAssetAssetsAssetIdGetRequestToJSON(
  getAssetAssetsAssetIdGetRequest: GetAssetAssetsAssetIdGetRequest,
): string {
  return JSON.stringify(
    GetAssetAssetsAssetIdGetRequest$outboundSchema.parse(
      getAssetAssetsAssetIdGetRequest,
    ),
  );
}

export function getAssetAssetsAssetIdGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAssetAssetsAssetIdGetRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAssetAssetsAssetIdGetRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAssetAssetsAssetIdGetRequest' from JSON`,
  );
}
