/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";

export type GetDeploymentsDeploymentsGetRequest = {
  environment: components.DeploymentEnvironment;
};

/** @internal */
export const GetDeploymentsDeploymentsGetRequest$inboundSchema: z.ZodType<
  GetDeploymentsDeploymentsGetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  environment: components.DeploymentEnvironment$inboundSchema,
});

/** @internal */
export type GetDeploymentsDeploymentsGetRequest$Outbound = {
  environment: string;
};

/** @internal */
export const GetDeploymentsDeploymentsGetRequest$outboundSchema: z.ZodType<
  GetDeploymentsDeploymentsGetRequest$Outbound,
  z.ZodTypeDef,
  GetDeploymentsDeploymentsGetRequest
> = z.object({
  environment: components.DeploymentEnvironment$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetDeploymentsDeploymentsGetRequest$ {
  /** @deprecated use `GetDeploymentsDeploymentsGetRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetDeploymentsDeploymentsGetRequest$inboundSchema;
  /** @deprecated use `GetDeploymentsDeploymentsGetRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetDeploymentsDeploymentsGetRequest$outboundSchema;
  /** @deprecated use `GetDeploymentsDeploymentsGetRequest$Outbound` instead. */
  export type Outbound = GetDeploymentsDeploymentsGetRequest$Outbound;
}
