/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetDeploymentDeploymentDeploymentIdGetRequest = {
  deploymentId: string;
};

/** @internal */
export const GetDeploymentDeploymentDeploymentIdGetRequest$inboundSchema:
  z.ZodType<
    GetDeploymentDeploymentDeploymentIdGetRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    deployment_id: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "deployment_id": "deploymentId",
    });
  });

/** @internal */
export type GetDeploymentDeploymentDeploymentIdGetRequest$Outbound = {
  deployment_id: string;
};

/** @internal */
export const GetDeploymentDeploymentDeploymentIdGetRequest$outboundSchema:
  z.ZodType<
    GetDeploymentDeploymentDeploymentIdGetRequest$Outbound,
    z.ZodTypeDef,
    GetDeploymentDeploymentDeploymentIdGetRequest
  > = z.object({
    deploymentId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      deploymentId: "deployment_id",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetDeploymentDeploymentDeploymentIdGetRequest$ {
  /** @deprecated use `GetDeploymentDeploymentDeploymentIdGetRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetDeploymentDeploymentDeploymentIdGetRequest$inboundSchema;
  /** @deprecated use `GetDeploymentDeploymentDeploymentIdGetRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetDeploymentDeploymentDeploymentIdGetRequest$outboundSchema;
  /** @deprecated use `GetDeploymentDeploymentDeploymentIdGetRequest$Outbound` instead. */
  export type Outbound = GetDeploymentDeploymentDeploymentIdGetRequest$Outbound;
}

export function getDeploymentDeploymentDeploymentIdGetRequestToJSON(
  getDeploymentDeploymentDeploymentIdGetRequest:
    GetDeploymentDeploymentDeploymentIdGetRequest,
): string {
  return JSON.stringify(
    GetDeploymentDeploymentDeploymentIdGetRequest$outboundSchema.parse(
      getDeploymentDeploymentDeploymentIdGetRequest,
    ),
  );
}

export function getDeploymentDeploymentDeploymentIdGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  GetDeploymentDeploymentDeploymentIdGetRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetDeploymentDeploymentDeploymentIdGetRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetDeploymentDeploymentDeploymentIdGetRequest' from JSON`,
  );
}
