/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetMachineSessionsSessionsGetRequest = {
  machineId: string;
};

/** @internal */
export const GetMachineSessionsSessionsGetRequest$inboundSchema: z.ZodType<
  GetMachineSessionsSessionsGetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  machine_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "machine_id": "machineId",
  });
});

/** @internal */
export type GetMachineSessionsSessionsGetRequest$Outbound = {
  machine_id: string;
};

/** @internal */
export const GetMachineSessionsSessionsGetRequest$outboundSchema: z.ZodType<
  GetMachineSessionsSessionsGetRequest$Outbound,
  z.ZodTypeDef,
  GetMachineSessionsSessionsGetRequest
> = z.object({
  machineId: z.string(),
}).transform((v) => {
  return remap$(v, {
    machineId: "machine_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetMachineSessionsSessionsGetRequest$ {
  /** @deprecated use `GetMachineSessionsSessionsGetRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetMachineSessionsSessionsGetRequest$inboundSchema;
  /** @deprecated use `GetMachineSessionsSessionsGetRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetMachineSessionsSessionsGetRequest$outboundSchema;
  /** @deprecated use `GetMachineSessionsSessionsGetRequest$Outbound` instead. */
  export type Outbound = GetMachineSessionsSessionsGetRequest$Outbound;
}
