/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type PostApiMachineEndpointRequestBody = {
    machineId: string;
    type: string;
};

/**
 * Create short lived machine endpoint
 */
export type PostApiMachineEndpointResponseBody = {
    url: string;
    gpu: string;
};

/** @internal */
export const PostApiMachineEndpointRequestBody$inboundSchema: z.ZodType<
    PostApiMachineEndpointRequestBody,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        machine_id: z.string(),
        type: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            machine_id: "machineId",
        });
    });

/** @internal */
export type PostApiMachineEndpointRequestBody$Outbound = {
    machine_id: string;
    type: string;
};

/** @internal */
export const PostApiMachineEndpointRequestBody$outboundSchema: z.ZodType<
    PostApiMachineEndpointRequestBody$Outbound,
    z.ZodTypeDef,
    PostApiMachineEndpointRequestBody
> = z
    .object({
        machineId: z.string(),
        type: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            machineId: "machine_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiMachineEndpointRequestBody$ {
    /** @deprecated use `PostApiMachineEndpointRequestBody$inboundSchema` instead. */
    export const inboundSchema = PostApiMachineEndpointRequestBody$inboundSchema;
    /** @deprecated use `PostApiMachineEndpointRequestBody$outboundSchema` instead. */
    export const outboundSchema = PostApiMachineEndpointRequestBody$outboundSchema;
    /** @deprecated use `PostApiMachineEndpointRequestBody$Outbound` instead. */
    export type Outbound = PostApiMachineEndpointRequestBody$Outbound;
}

/** @internal */
export const PostApiMachineEndpointResponseBody$inboundSchema: z.ZodType<
    PostApiMachineEndpointResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    url: z.string(),
    gpu: z.string(),
});

/** @internal */
export type PostApiMachineEndpointResponseBody$Outbound = {
    url: string;
    gpu: string;
};

/** @internal */
export const PostApiMachineEndpointResponseBody$outboundSchema: z.ZodType<
    PostApiMachineEndpointResponseBody$Outbound,
    z.ZodTypeDef,
    PostApiMachineEndpointResponseBody
> = z.object({
    url: z.string(),
    gpu: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiMachineEndpointResponseBody$ {
    /** @deprecated use `PostApiMachineEndpointResponseBody$inboundSchema` instead. */
    export const inboundSchema = PostApiMachineEndpointResponseBody$inboundSchema;
    /** @deprecated use `PostApiMachineEndpointResponseBody$outboundSchema` instead. */
    export const outboundSchema = PostApiMachineEndpointResponseBody$outboundSchema;
    /** @deprecated use `PostApiMachineEndpointResponseBody$Outbound` instead. */
    export type Outbound = PostApiMachineEndpointResponseBody$Outbound;
}
