/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateDeploymentDeploymentDeploymentIdPatchRequest = {
  deploymentId: string;
  deploymentUpdate: components.DeploymentUpdate;
};

/** @internal */
export const UpdateDeploymentDeploymentDeploymentIdPatchRequest$inboundSchema:
  z.ZodType<
    UpdateDeploymentDeploymentDeploymentIdPatchRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    deployment_id: z.string(),
    DeploymentUpdate: components.DeploymentUpdate$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "deployment_id": "deploymentId",
      "DeploymentUpdate": "deploymentUpdate",
    });
  });

/** @internal */
export type UpdateDeploymentDeploymentDeploymentIdPatchRequest$Outbound = {
  deployment_id: string;
  DeploymentUpdate: components.DeploymentUpdate$Outbound;
};

/** @internal */
export const UpdateDeploymentDeploymentDeploymentIdPatchRequest$outboundSchema:
  z.ZodType<
    UpdateDeploymentDeploymentDeploymentIdPatchRequest$Outbound,
    z.ZodTypeDef,
    UpdateDeploymentDeploymentDeploymentIdPatchRequest
  > = z.object({
    deploymentId: z.string(),
    deploymentUpdate: components.DeploymentUpdate$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      deploymentId: "deployment_id",
      deploymentUpdate: "DeploymentUpdate",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateDeploymentDeploymentDeploymentIdPatchRequest$ {
  /** @deprecated use `UpdateDeploymentDeploymentDeploymentIdPatchRequest$inboundSchema` instead. */
  export const inboundSchema =
    UpdateDeploymentDeploymentDeploymentIdPatchRequest$inboundSchema;
  /** @deprecated use `UpdateDeploymentDeploymentDeploymentIdPatchRequest$outboundSchema` instead. */
  export const outboundSchema =
    UpdateDeploymentDeploymentDeploymentIdPatchRequest$outboundSchema;
  /** @deprecated use `UpdateDeploymentDeploymentDeploymentIdPatchRequest$Outbound` instead. */
  export type Outbound =
    UpdateDeploymentDeploymentDeploymentIdPatchRequest$Outbound;
}

export function updateDeploymentDeploymentDeploymentIdPatchRequestToJSON(
  updateDeploymentDeploymentDeploymentIdPatchRequest:
    UpdateDeploymentDeploymentDeploymentIdPatchRequest,
): string {
  return JSON.stringify(
    UpdateDeploymentDeploymentDeploymentIdPatchRequest$outboundSchema.parse(
      updateDeploymentDeploymentDeploymentIdPatchRequest,
    ),
  );
}

export function updateDeploymentDeploymentDeploymentIdPatchRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateDeploymentDeploymentDeploymentIdPatchRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateDeploymentDeploymentDeploymentIdPatchRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateDeploymentDeploymentDeploymentIdPatchRequest' from JSON`,
  );
}
