/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UploadAssetFileAssetsUploadPostRequest = {
  /**
   * Parent folder path
   */
  parentPath?: string | undefined;
  bodyUploadAssetFileAssetsUploadPost:
    components.BodyUploadAssetFileAssetsUploadPost;
};

/** @internal */
export const UploadAssetFileAssetsUploadPostRequest$inboundSchema: z.ZodType<
  UploadAssetFileAssetsUploadPostRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  parent_path: z.string().default("/"),
  Body_upload_asset_file_assets_upload_post:
    components.BodyUploadAssetFileAssetsUploadPost$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "parent_path": "parentPath",
    "Body_upload_asset_file_assets_upload_post":
      "bodyUploadAssetFileAssetsUploadPost",
  });
});

/** @internal */
export type UploadAssetFileAssetsUploadPostRequest$Outbound = {
  parent_path: string;
  Body_upload_asset_file_assets_upload_post:
    components.BodyUploadAssetFileAssetsUploadPost$Outbound;
};

/** @internal */
export const UploadAssetFileAssetsUploadPostRequest$outboundSchema: z.ZodType<
  UploadAssetFileAssetsUploadPostRequest$Outbound,
  z.ZodTypeDef,
  UploadAssetFileAssetsUploadPostRequest
> = z.object({
  parentPath: z.string().default("/"),
  bodyUploadAssetFileAssetsUploadPost:
    components.BodyUploadAssetFileAssetsUploadPost$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    parentPath: "parent_path",
    bodyUploadAssetFileAssetsUploadPost:
      "Body_upload_asset_file_assets_upload_post",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UploadAssetFileAssetsUploadPostRequest$ {
  /** @deprecated use `UploadAssetFileAssetsUploadPostRequest$inboundSchema` instead. */
  export const inboundSchema =
    UploadAssetFileAssetsUploadPostRequest$inboundSchema;
  /** @deprecated use `UploadAssetFileAssetsUploadPostRequest$outboundSchema` instead. */
  export const outboundSchema =
    UploadAssetFileAssetsUploadPostRequest$outboundSchema;
  /** @deprecated use `UploadAssetFileAssetsUploadPostRequest$Outbound` instead. */
  export type Outbound = UploadAssetFileAssetsUploadPostRequest$Outbound;
}

export function uploadAssetFileAssetsUploadPostRequestToJSON(
  uploadAssetFileAssetsUploadPostRequest:
    UploadAssetFileAssetsUploadPostRequest,
): string {
  return JSON.stringify(
    UploadAssetFileAssetsUploadPostRequest$outboundSchema.parse(
      uploadAssetFileAssetsUploadPostRequest,
    ),
  );
}

export function uploadAssetFileAssetsUploadPostRequestFromJSON(
  jsonString: string,
): SafeParseResult<UploadAssetFileAssetsUploadPostRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UploadAssetFileAssetsUploadPostRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadAssetFileAssetsUploadPostRequest' from JSON`,
  );
}
