/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  MediaItem,
  MediaItem$inboundSchema,
  MediaItem$Outbound,
  MediaItem$outboundSchema,
} from "./mediaitem.js";

export type ApiRoutesTypesWorkflowRunOutputModel2 = {
  id: string;
  runId: string;
  data: { [k: string]: Array<MediaItem> };
  createdAt: Date;
  updatedAt: Date;
  type?: string | null | undefined;
  nodeId?: string | null | undefined;
};

/** @internal */
export const ApiRoutesTypesWorkflowRunOutputModel2$inboundSchema: z.ZodType<
  ApiRoutesTypesWorkflowRunOutputModel2,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  run_id: z.string(),
  data: z.record(z.array(MediaItem$inboundSchema)),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  type: z.nullable(z.string()).optional(),
  node_id: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "run_id": "runId",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "node_id": "nodeId",
  });
});

/** @internal */
export type ApiRoutesTypesWorkflowRunOutputModel2$Outbound = {
  id: string;
  run_id: string;
  data: { [k: string]: Array<MediaItem$Outbound> };
  created_at: string;
  updated_at: string;
  type?: string | null | undefined;
  node_id?: string | null | undefined;
};

/** @internal */
export const ApiRoutesTypesWorkflowRunOutputModel2$outboundSchema: z.ZodType<
  ApiRoutesTypesWorkflowRunOutputModel2$Outbound,
  z.ZodTypeDef,
  ApiRoutesTypesWorkflowRunOutputModel2
> = z.object({
  id: z.string(),
  runId: z.string(),
  data: z.record(z.array(MediaItem$outboundSchema)),
  createdAt: z.date().transform(v => v.toISOString()),
  updatedAt: z.date().transform(v => v.toISOString()),
  type: z.nullable(z.string()).optional(),
  nodeId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    runId: "run_id",
    createdAt: "created_at",
    updatedAt: "updated_at",
    nodeId: "node_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiRoutesTypesWorkflowRunOutputModel2$ {
  /** @deprecated use `ApiRoutesTypesWorkflowRunOutputModel2$inboundSchema` instead. */
  export const inboundSchema =
    ApiRoutesTypesWorkflowRunOutputModel2$inboundSchema;
  /** @deprecated use `ApiRoutesTypesWorkflowRunOutputModel2$outboundSchema` instead. */
  export const outboundSchema =
    ApiRoutesTypesWorkflowRunOutputModel2$outboundSchema;
  /** @deprecated use `ApiRoutesTypesWorkflowRunOutputModel2$Outbound` instead. */
  export type Outbound = ApiRoutesTypesWorkflowRunOutputModel2$Outbound;
}
