/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { blobLikeSchema } from "../../types/blobs.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FileT = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type BodyUploadFileFileUploadPost = {
  file: FileT | Blob;
};

/** @internal */
export const FileT$inboundSchema: z.ZodType<FileT, z.ZodTypeDef, unknown> = z
  .object({
    fileName: z.string(),
    content: z.union([
      z.instanceof(ReadableStream<Uint8Array>),
      z.instanceof(Blob),
      z.instanceof(ArrayBuffer),
      z.instanceof(Uint8Array),
    ]),
  });

/** @internal */
export type FileT$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const FileT$outboundSchema: z.ZodType<
  FileT$Outbound,
  z.ZodTypeDef,
  FileT
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FileT$ {
  /** @deprecated use `FileT$inboundSchema` instead. */
  export const inboundSchema = FileT$inboundSchema;
  /** @deprecated use `FileT$outboundSchema` instead. */
  export const outboundSchema = FileT$outboundSchema;
  /** @deprecated use `FileT$Outbound` instead. */
  export type Outbound = FileT$Outbound;
}

export function fileTToJSON(fileT: FileT): string {
  return JSON.stringify(FileT$outboundSchema.parse(fileT));
}

export function fileTFromJSON(
  jsonString: string,
): SafeParseResult<FileT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileT' from JSON`,
  );
}

/** @internal */
export const BodyUploadFileFileUploadPost$inboundSchema: z.ZodType<
  BodyUploadFileFileUploadPost,
  z.ZodTypeDef,
  unknown
> = z.object({
  file: z.lazy(() => FileT$inboundSchema),
});

/** @internal */
export type BodyUploadFileFileUploadPost$Outbound = {
  file: FileT$Outbound | Blob;
};

/** @internal */
export const BodyUploadFileFileUploadPost$outboundSchema: z.ZodType<
  BodyUploadFileFileUploadPost$Outbound,
  z.ZodTypeDef,
  BodyUploadFileFileUploadPost
> = z.object({
  file: z.lazy(() => FileT$outboundSchema).or(blobLikeSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BodyUploadFileFileUploadPost$ {
  /** @deprecated use `BodyUploadFileFileUploadPost$inboundSchema` instead. */
  export const inboundSchema = BodyUploadFileFileUploadPost$inboundSchema;
  /** @deprecated use `BodyUploadFileFileUploadPost$outboundSchema` instead. */
  export const outboundSchema = BodyUploadFileFileUploadPost$outboundSchema;
  /** @deprecated use `BodyUploadFileFileUploadPost$Outbound` instead. */
  export type Outbound = BodyUploadFileFileUploadPost$Outbound;
}

export function bodyUploadFileFileUploadPostToJSON(
  bodyUploadFileFileUploadPost: BodyUploadFileFileUploadPost,
): string {
  return JSON.stringify(
    BodyUploadFileFileUploadPost$outboundSchema.parse(
      bodyUploadFileFileUploadPost,
    ),
  );
}

export function bodyUploadFileFileUploadPostFromJSON(
  jsonString: string,
): SafeParseResult<BodyUploadFileFileUploadPost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BodyUploadFileFileUploadPost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BodyUploadFileFileUploadPost' from JSON`,
  );
}
