/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteSessionResponse = {
  success: boolean;
};

/** @internal */
export const DeleteSessionResponse$inboundSchema: z.ZodType<
  DeleteSessionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
});

/** @internal */
export type DeleteSessionResponse$Outbound = {
  success: boolean;
};

/** @internal */
export const DeleteSessionResponse$outboundSchema: z.ZodType<
  DeleteSessionResponse$Outbound,
  z.ZodTypeDef,
  DeleteSessionResponse
> = z.object({
  success: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteSessionResponse$ {
  /** @deprecated use `DeleteSessionResponse$inboundSchema` instead. */
  export const inboundSchema = DeleteSessionResponse$inboundSchema;
  /** @deprecated use `DeleteSessionResponse$outboundSchema` instead. */
  export const outboundSchema = DeleteSessionResponse$outboundSchema;
  /** @deprecated use `DeleteSessionResponse$Outbound` instead. */
  export type Outbound = DeleteSessionResponse$Outbound;
}

export function deleteSessionResponseToJSON(
  deleteSessionResponse: DeleteSessionResponse,
): string {
  return JSON.stringify(
    DeleteSessionResponse$outboundSchema.parse(deleteSessionResponse),
  );
}

export function deleteSessionResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteSessionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteSessionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteSessionResponse' from JSON`,
  );
}
