/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const GPUType = {
  Cpu: "CPU",
  T4: "T4",
  L4: "L4",
  A10G: "A10G",
  L40S: "L40S",
  A100: "A100",
  A10080Gb: "A100-80GB",
  H100: "H100",
} as const;
export type GPUType = ClosedEnum<typeof GPUType>;

/** @internal */
export const GPUType$inboundSchema: z.ZodNativeEnum<typeof GPUType> = z
  .nativeEnum(GPUType);

/** @internal */
export const GPUType$outboundSchema: z.ZodNativeEnum<typeof GPUType> =
  GPUType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GPUType$ {
  /** @deprecated use `GPUType$inboundSchema` instead. */
  export const inboundSchema = GPUType$inboundSchema;
  /** @deprecated use `GPUType$outboundSchema` instead. */
  export const outboundSchema = GPUType$outboundSchema;
}
