/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type WorkflowRunWebhookResponse = {
  status: string;
};

/** @internal */
export const WorkflowRunWebhookResponse$inboundSchema: z.ZodType<
  WorkflowRunWebhookResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
});

/** @internal */
export type WorkflowRunWebhookResponse$Outbound = {
  status: string;
};

/** @internal */
export const WorkflowRunWebhookResponse$outboundSchema: z.ZodType<
  WorkflowRunWebhookResponse$Outbound,
  z.ZodTypeDef,
  WorkflowRunWebhookResponse
> = z.object({
  status: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkflowRunWebhookResponse$ {
  /** @deprecated use `WorkflowRunWebhookResponse$inboundSchema` instead. */
  export const inboundSchema = WorkflowRunWebhookResponse$inboundSchema;
  /** @deprecated use `WorkflowRunWebhookResponse$outboundSchema` instead. */
  export const outboundSchema = WorkflowRunWebhookResponse$outboundSchema;
  /** @deprecated use `WorkflowRunWebhookResponse$Outbound` instead. */
  export type Outbound = WorkflowRunWebhookResponse$Outbound;
}
